name: CI

env:
  pnpm_store_path: ${{github.workspace}}/.pnpm-store

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pnpmstore:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [ 14 ]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set pnpm store directory
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 5.18.9
          run_install: |
            args: [--frozen-lockfile]
      - name: check pnpm store
        if: steps.pnpm-store.outputs.cache-hit != 'true'
        run: pnpm store status

  lint:
    needs: pnpmstore

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14 ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set pnpm store directory
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 5.18.9
          run_install: |
            args: [--frozen-lockfile]
      - name: build
        run: pnpm run ci:build
      - name: lint
        run: pnpm lint

  audit:
    needs: pnpmstore

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14 ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set pnpm store directory
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 5.18.9
          run_install: |
            args: [--frozen-lockfile]
      - name: audit
        run: pnpm audit

  test:
    needs: pnpmstore

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 14 ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set pnpm store directory
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 5.18.9
          run_install: |
            args: [--frozen-lockfile]
      - name: build
        run: pnpm run ci:build
#      - name: run tests
#        run: pnpm ci:test

  build:
    needs: pnpmstore
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14 ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set pnpm store directory
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 5.18.9
          run_install: |
            args: [--frozen-lockfile]
      - name: build
        run: pnpm run build
